name: Upload Bannerlord DLLs

on:
  workflow_dispatch:  # Manual trigger from the GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload DLLs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: BannerlordDLLs
          path: lib/
